WebApplication1/WebApplication1/Models/Material/Supplier.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models.Material
{
    public class Supplier
    {
        public string SupplierID { get; set; }
        public string FullName { get; set; }
    }
}

WebApplication1/WebApplication1/Models/Supplier/Supplier.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication1.Models.Supplier
{
    public class Supplier
    {
        [Required]
        [Display(Name = "廠商編號")]
        [StringLength(10, ErrorMessage = "{0}的長度至少必須為{2}的字元。", MinimumLength = 1)]
        public string SupplierID { get; set; }

        [Display(Name = "廠商名稱")]
        [StringLength(50, ErrorMessage = "{0}的長度至少必須為{2}的字元。", MinimumLength = 1)]
        public string FullName { get; set; }




        public static List<Models.Supplier.Supplier> Get_Supplier(string id)
        {
            List<Models.Supplier.Supplier> result = new List<Models.Supplier.Supplier>();

            using (var conn = new MySqlConnection(GlobalFunction.GlobalConnString))
            {

                conn.Open();

                using (var command = conn.CreateCommand())
                {
                    command.CommandText = "SELECT SupplierID,FullName  FROM Supplier WHERE SupplierID = @ID And AFlag = 0";
                    command.Parameters.AddWithValue("@ID", id);

                    using (var reader = command.ExecuteReader())
                    {
                        if (reader.HasRows)
                        {

                            while (reader.Read())
                            {
                                result.Add(new Models.Supplier.Supplier()
                                {
                                    SupplierID = (string)reader["SupplierID"],
                                    FullName = (reader.IsDBNull(reader.GetOrdinal("FullName"))) ? "" : (string)reader["FullName"],
                                });
                            }
                            return result;
                        }
                        else
                        {
                            return result;
                        }
                    }
                }
            }
        }

        public static List<Models.Supplier.Supplier> Get_Supplier()
        {

            List<Models.Supplier.Supplier> result = new List<Models.Supplier.Supplier>();
            string connectionString = GlobalFunction.GlobalConnString;

            using (var conn = new MySqlConnection(connectionString))
            {

                conn.Open();

                using (var command = conn.CreateCommand())
                {
                    command.CommandText = "SELECT SupplierID,FullName  FROM Supplier WHERE  AFlag = 0";

                    using (var reader = command.ExecuteReader())
                    {
                        if (reader.HasRows)
                        {
                            while (reader.Read())
                            {
                                result.Add(new Models.Supplier.Supplier()
                                {
                                    SupplierID = (string)reader["SupplierID"],
                                    FullName = (reader.IsDBNull(reader.GetOrdinal("FullName"))) ? "" : (string)reader["FullName"],
                                });
                            }
                            return result;
                        }
                        else
                        {
                            return result;
                        }
                    }
                }
            }
        }

        public Models.Supplier.Supplier Get_Edit_Supplier(string id)
        {
            var result = new Models.Supplier.Supplier();

            using (var conn = new MySqlConnection(GlobalFunction.GlobalConnString))
            {

                conn.Open();

                using (var command = conn.CreateCommand())
                {
                    command.CommandText = "SELECT SupplierID,FullName  FROM Supplier WHERE SupplierID = @ID ";
                    command.Parameters.AddWithValue("@ID", id);

                    using (var reader = command.ExecuteReader())
                    {
                        if (reader.HasRows)
                        {

                            while (reader.Read())
                            {

                                result = new Models.Supplier.Supplier()
                                {
                                    SupplierID = (string)reader["SupplierID"],
                                    FullName = (reader.IsDBNull(reader.GetOrdinal("FullName"))) ? "" : (string)reader["FullName"],
                                };
                            }

                            return result;
                        }
                        else
                        {
                            return result;
                        }
                    }
                }
            }
        }


        public bool Patch_Supplier(Models.Supplier.Supplier supplier, string InputUserID)
        {
            var result = false;
            using (var conn = new MySqlConnection(GlobalFunction.GlobalConnString))
            {
                conn.Open();

                using (var command = conn.CreateCommand())
                {
                    command.CommandText = "Update Supplier Set FullName = @FullName,EmployeeID =@EmployeeID,ModifyDate = Now() Where SupplierID = @SupplierID";
                    command.Parameters.AddWithValue("@SupplierID", supplier.SupplierID);
                    command.Parameters.AddWithValue("@FullName", supplier.FullName);
                    command.Parameters.AddWithValue("@EmployeeID", InputUserID);
                    command.ExecuteNonQuery();

                    result = true;
                    return result;
                }
            }
        }


        public bool Delete_Supplier(string id)
        {
            var result = false;
            using (var conn = new MySqlConnection(GlobalFunction.GlobalConnString))
            {
                conn.Open();

                using (var command = conn.CreateCommand())
                {
                    command.CommandText = "Update Supplier Set AFlag = -1 Where SupplierID = @SupplierID";
                    command.Parameters.AddWithValue("@SupplierID", id);
                    command.ExecuteNonQuery();
                    result = true;
                    return result;
                }
            }
        }

        public bool IsSupplieridExist(string supplierId)
        {

            string connectionString = GlobalFunction.GlobalConnString;

            using (var conn = new MySqlConnection(connectionString))
            {

                conn.Open();

                using (var command = conn.CreateCommand())
                {
                    command.CommandText = "SELECT SupplierID  FROM Supplier WHERE SupplierID = @SupplierID";
                    command.Parameters.AddWithValue("@SupplierID", supplierId);

                    using (var reader = command.ExecuteReader())
                    {
                        if (reader.HasRows)
                        {
                            return false;
                        }
                        else
                        {
                            return true;
                        }
                    }
                }
            }

        }

        public bool Post_Supplier(Models.Supplier.Supplier supplier,string InputUserID)
        {
            var result = false;
            using (var conn = new MySqlConnection(GlobalFunction.GlobalConnString))
            {
                conn.Open();

                using (var command = conn.CreateCommand())
                {
                    command.CommandText = "Insert Into Supplier (SupplierID,AccountID,FullName,InputDate,EmployeeID) VALUES(@SupplierID,@AccountID,@FullName,CURDATE(),@InputUser)";
                    command.Parameters.AddWithValue("@SupplierID", supplier.SupplierID);
                    command.Parameters.AddWithValue("@AccountID", supplier.SupplierID);
                    command.Parameters.AddWithValue("@FullName", supplier.FullName);
                    command.Parameters.AddWithValue("@InputUser", InputUserID);
                    command.ExecuteNonQuery();
   
                    result = true;
                }
            }
            return result;
        }

    }
}

WebApplication1/WebApplication1/Models/Supplier/SupplierList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models.Supplier
{
    public class SupplierList
    {
    }

    public static class SupplierSearch
    {
        public static List<Models.Supplier.Supplier> SupplierList;
    }
}

WebApplication1/WebApplication1/Controllers/SupplierController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Infrastructure.MemberResults;

namespace WebApplication1.Controllers
{
    public class SupplierController : Controller
    {
        // GET: Supplier
        public ActionResult Index(string id, int page = 1, int pageSize = 15)
        {
            if ((string)Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Login");
            }


            String SearchString = id;


            try
            {
                if (!String.IsNullOrEmpty(SearchString))
                {
                    page = 1;
                    pageSize = 15;
                    Models.Supplier.SupplierSearch.SupplierList = Models.Supplier.Supplier.Get_Supplier(SearchString);
                    var suppliers = Models.Supplier.SupplierSearch.SupplierList.OrderBy(x => x.SupplierID).ToPagedList(page, pageSize); 
                    return View(suppliers);
                }
                else
                {
                    Models.Supplier.SupplierSearch.SupplierList = Models.Supplier.Supplier.Get_Supplier();
                    var result = Models.Supplier.SupplierSearch.SupplierList.OrderBy(x => x.SupplierID).ToPagedList(page, pageSize);
                    return View(result);
                }
            }
            catch (Exception e)
            {
                ViewBag.ResultMessage = e.ToString();
                return View();
            }

        }

        public ActionResult Edit(string id)
        {
            try
            {
                var result = new Models.Supplier.Supplier().Get_Edit_Supplier(id);
                if (result != default(Models.Supplier.Supplier))
                {
                    return View(result);
                }
                else
                {   //如果沒有資料則顯示錯誤訊息並導回Index頁面
                    TempData["resultMessage"] = "資料有誤，請重新操作";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                ViewBag.ResultMessage = e.ToString();
                return View();
            }
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Models.Supplier.Supplier postback)
        {
            try
            {
           
                if (this.ModelState.IsValid)
                {
                    var result = new Models.Supplier.Supplier().Patch_Supplier(postback, (string)Session["UserID"]);
                    if (result)
                    {
                        TempData["ResultMessage"] = String.Format("廠商[{0}]成功編輯", postback.SupplierID);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.ResultMessage = "資料有誤，請檢查";
                        return View(postback);
                    }

                }
                else
                {
                    ViewBag.ResultMessage = "資料有誤，請檢查";
                    return View(postback);
                }
            }
            catch (Exception e)
            {
                ViewBag.ResultMessage = e.ToString();
                return View();
            }
        }


        public ActionResult Delete(string id)
        {

            try
            {
                var result = new Models.Supplier.Supplier().Delete_Supplier(id);
                if (result) //判斷此id是否有資料
                {
                    TempData["ResultMessage"] = String.Format("會員[{0}]成功刪除", id);
                    return RedirectToAction("Index");
                }
                else
                {   //如果沒有資料則顯示錯誤訊息並導回Index頁面
                    TempData["ResultMessage"] = "資料有誤，請重新操作";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                ViewBag.ResultMessage = e.ToString();
                return View();
            }

        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult HasData()
        {
            JObject jo = new JObject();
            bool result = !Models.Supplier.SupplierSearch.SupplierList.Count.Equals(0);
            jo.Add("Msg", result.ToString());
            return Content(JsonConvert.SerializeObject(jo), "application/json");
        }

        public ActionResult Export()
        {
            var exportSpource = this.GetExportDataWithAllColumns();
            var dt = JsonConvert.DeserializeObject<DataTable>(exportSpource.ToString());

            var exportFileName =
                string.Concat("SupplierData_", DateTime.Now.ToString("yyyyMMddHHmmss"), ".xlsx");

            return new ExportExcelResult
            {
                SheetName = "廠商資料",
                FileName = exportFileName,
                ExportData = dt
            };
        }

        private JArray GetExportDataWithAllColumns()
        {
            var query = Models.Supplier.SupplierSearch.SupplierList.OrderBy(x => x.SupplierID);
            JArray jObjects = new JArray();

            foreach (var item in query)
            {
                var jo = new JObject
                {
                    {"SupplierID", item.SupplierID},
                    {"FullName", item.FullName},
                };
                jObjects.Add(jo);
            }
            return jObjects;
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Models.Supplier.Supplier postback)
        {

            try
            {
             
                if (this.ModelState.IsValid)
                {
                    if (!new Models.Supplier.Supplier().IsSupplieridExist(postback.SupplierID))
                    {
                        ViewBag.ResultMessage = "廠商編號已存在";
                        return View(postback);
                    }
                    else
                    {
                        var result = new Models.Supplier.Supplier().Post_Supplier(postback ,(string)Session["UserID"]);
                        if (result)
                        {
                            TempData["ResultMessage"] = String.Format("廠商[{0}]成功新增", postback.SupplierID);

                            return RedirectToAction("Index");
                        }
                        else
                        {
                            ViewBag.ResultMessage = "資料有誤，請檢查";
                            return View(postback);
                        }
                    }

                }
                else
                {
                    ViewBag.ResultMessage = "資料有誤，請檢查";
                    return View(postback);
                }
            }
            catch (Exception e)
            {
                ViewBag.ResultMessage = e.ToString();
                return View();
            }
        }
    }



}

WebApplication1/WebApplication1/Views/Supplier/Create.cshtml
@model WebApplication1.Models.Supplier.Supplier

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}



@using (Html.BeginForm("Create", "Supplier", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>廠商資料新增作業</h2>
        <hr />

        @if (ViewBag.ResultMessage != null)//判斷如果有訊息，則顯示。
        {
            //@Html.Label("info", (string)ViewBag.ResultMessage, new { @class = "text-info" })
            <script type="text/javascript">
            var message = @Html.Raw(Json.Encode(ViewBag.ResultMessage));
            alert(message);
            </script>
        }

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.SupplierID, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SupplierID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SupplierID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

     
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="存檔" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回清單", "Index")
</div>

WebApplication1/WebApplication1/Views/Supplier/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2>Delete</h2>

WebApplication1/WebApplication1/Views/Supplier/Edit.cshtml
@model WebApplication1.Models.Supplier.Supplier

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

@if (ViewBag.ResultMessage != null)//判斷如果有訊息，則顯示。
{
    //@Html.Label("info", (string)ViewBag.ResultMessage, new { @class = "text-info" })
    <script type="text/javascript">
            var message = @Html.Raw(Json.Encode(ViewBag.ResultMessage));
            alert(message);
    </script>
}

@using (Html.BeginForm("Edit", "Supplier", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <br></br>
        <h2>廠商資料修改作業</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SupplierID)


        <div class="form-group">
            @Html.LabelFor(model => model.SupplierID, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SupplierID, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.SupplierID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="存檔" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回清單", "Index")
</div>

WebApplication1/WebApplication1/Views/Supplier/Index.cshtml
@model IEnumerable<WebApplication1.Models.Supplier.Supplier>
@using PagedList.Mvc;
@using PagedList;


@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<h1>廠商資料管理作業</h1>
<br />

@if (ViewBag.ResultMessage != null)//判斷如果有訊息，則顯示。
{
    <script type="text/javascript">
            var message = @Html.Raw(Json.Encode(ViewBag.ResultMessage));
            alert(message);
    </script>
}
<div class="container">
    <div class="row">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="table-responsive">
                <div id="toolbar">
                    <form class="form-inline">
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon">廠商編號</div>
                                <input type="text" class="form-control" name="id" id="searchTexts" placeholder="請輸入廠商編號">
                                <div class="column">
                                    <button type="submit" class="btn btn-primary queryButton"> 搜尋</button>
                                    @Html.ActionLink("新增廠商", "Create", new { }, new { @class = "btn btn-primary" })
                                    <button type="button" class="btn btn-primary" id="ButtonExport" name="ButtonExport" onclick="ExportClick('Supplier')">
                                        匯出資料
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div>

        }
    </div>
</div>



<table class="table">
    <tr>
        <th width="70">
            操作
        </th>
        <th width="70">
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().SupplierID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().FullName)
        </th>
        <th>

        </th>
    </tr>

    @foreach (var md in this.Model)
    {
<tr>
    <td>
        @Html.ActionLink("編輯", "Edit", new { id = md.SupplierID }, new { @class = "glyphicon glyphicon-pencil" })
    </td>
    <td>
        @Html.ActionLink("刪除", "Delete", new { id = md.SupplierID }, new { @class = "glyphicon glyphicon-trash", @onclick = "return Confirm_Form('" + md.SupplierID + "')" })
    </td>
    <td>@md.SupplierID</td>
    <td>@md.FullName</td>
    <td></td>
</tr>
    }
</table>
@Html.PagedListPager((IPagedList)Model, x => Url.Action("Index", new { page = x }))

@section scripts
{
    <script type="text/javascript">
        function Confirm_Form(SupplierID) {
            var message = "您確定要刪除廠商編號" + SupplierID + "嗎?";
            if (!confirm(message))
                return false;
        }
    </script>

    <script src="@RouteJs.RouteJsHandler.HandlerUrl"></script>
    <script src="~/Scripts/Export.js"></script>
    <script src="~/Scripts/bootbox.min.js"></script>
}