WebApplication1/WebApplication1/Models/Member/MemberList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models.Member
{
    public class MemberList
    {
    }

    public static class MemberSearch
    {
        public static List<Models.Member.Member> MemberList;
    }
}

WebApplication1/WebApplication1/Controllers/MemberController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Infrastructure.MemberResults;

namespace WebApplication1.Controllers
{

    public class MemberController : Controller
    {
        // GET: Member

        public ActionResult Index(string id, int page = 1, int pageSize = 15)
        {
            if ((string)Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            
            
            String SearchString = id;


            try
            {
                if (!String.IsNullOrEmpty(SearchString))
                {
                    page = 1;
                    pageSize = 15;
                    Models.Member.MemberSearch.MemberList = Models.Member.Member.Get_Member(SearchString);
                    var member = Models.Member.MemberSearch.MemberList.OrderBy(x => x.MemberID).ToPagedList(page, pageSize); ;
                    return View(member);
                }
                else
                {
                    Models.Member.MemberSearch.MemberList = Models.Member.Member.Get_Member();
                    var result = Models.Member.MemberSearch.MemberList.OrderBy(x => x.MemberID).ToPagedList(page, pageSize);
                    return View(result);
                }
            }
            catch (Exception e)
            {
                ViewBag.ResultMessage = e.ToString();
                return View();
            }

        }


        public ActionResult Edit(string id)
        {
            try
            {
                var result = new Models.Member.Member().Get_Edit_Member(id);
                if (result != default(Models.Member.Member))
                {
                    return View(result);
                }
                else
                {   //如果沒有資料則顯示錯誤訊息並導回Index頁面
                    TempData["resultMessage"] = "資料有誤，請重新操作";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                ViewBag.ResultMessage = e.ToString();
                return View();
            }
        }
     

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Models.Member.Member postback, HttpPostedFileBase file)
        {
            try
            {
                byte[] FileBytes = null;
                if (file != null)
                {

                    using (MemoryStream ms = new MemoryStream())
                    {
                        file.InputStream.CopyTo(ms);
                        FileBytes = ms.GetBuffer();
                    }


                    if (file.ContentLength > 2048000)
                    {
                        ViewBag.ResultMessage = "檔案大小不可超過2M";
                        return View(postback);
                    }

                    if (file.FileName.Length > 50)
                    {
                        ViewBag.ResultMessage = "檔案名稱太長";
                        return View(postback);
                    }


                    //檔案是否為圖片
                    if (!Models.Member.Member.IsPicture(file.FileName))
                    {
                        ViewBag.ResultMessage = "檔案不為圖片";
                        return View(postback);
                    }

                    //檔案是否為圖片
                    if (Models.Member.Member.IsImage(file) == null)
                    {
                        ViewBag.ResultMessage = "檔案不為圖片";
                        return View(postback);
                    }
                }

                if (this.ModelState.IsValid)
                {
                    var result = new Models.Member.Member().Patch_Member(postback, file, FileBytes, (string)Session["UserID"]);
                    if (result)
                    {
                        TempData["ResultMessage"] = String.Format("會員[{0}]成功編輯", postback.MemberID);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.ResultMessage = "資料有誤，請檢查";
                        return View(postback);
                    }

                }
                else
                {
                    ViewBag.ResultMessage = "資料有誤，請檢查";
                    return View(postback);
                }
            }
            catch (Exception e)
            {
                ViewBag.ResultMessage = e.ToString();
                return View();
            }
        }

      
        public ActionResult Delete(string id)
        {

            try
            {
                var result = new Models.Member.Member().Delete_Member(id);
                if (result) //判斷此id是否有資料
                {
                    TempData["ResultMessage"] = String.Format("會員[{0}]成功刪除", id);
                    return RedirectToAction("Index");
                }
                else
                {   //如果沒有資料則顯示錯誤訊息並導回Index頁面
                    TempData["ResultMessage"] = "資料有誤，請重新操作";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                ViewBag.ResultMessage = e.ToString();
                return View();
            }

        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult HasData()
        {
            JObject jo = new JObject();
            bool result = !Models.Member.MemberSearch.MemberList.Count.Equals(0);
            jo.Add("Msg", result.ToString());
            return Content(JsonConvert.SerializeObject(jo), "application/json");
        }

        public ActionResult Export()
        {
            var exportSpource = this.GetExportDataWithAllColumns();
            var dt = JsonConvert.DeserializeObject<DataTable>(exportSpource.ToString());

            var exportFileName =
                string.Concat("MemberData_", DateTime.Now.ToString("yyyyMMddHHmmss"), ".xlsx");

            return new ExportExcelResult
            {
                SheetName = "會員資料",
                FileName = exportFileName,
                ExportData = dt
            };
        }

        private JArray GetExportDataWithAllColumns()
        {
            //var query = db.Customers.OrderBy(x => x.CustomerID);
            var query = Models.Member.MemberSearch.MemberList.OrderBy(x => x.MemberID);
            JArray jObjects = new JArray();

            foreach (var item in query)
            {
                var jo = new JObject
                {
                    {"MemberID", item.MemberID},
                    {"MemberName", item.MemberName},
                    {"MobilPhone", item.MobilPhone},
                    {"EMail", item.EMail},
                };
                jObjects.Add(jo);
            }
            return jObjects;
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Models.Member.Member postback, HttpPostedFileBase file)
        {

            try
            {
                byte[] FileBytes = null;

                if (file != null)
                {

                    using (MemoryStream ms = new MemoryStream())
                    {
                        file.InputStream.CopyTo(ms);
                        FileBytes = ms.GetBuffer();
                    }


                    if (file.ContentLength > 2048000)
                    {
                        ViewBag.ResultMessage = "檔案大小不可超過2M";
                        return View(postback);
                    }


                    if (file.FileName.Length > 50)
                    {
                        ViewBag.ResultMessage = "檔案名稱太長";
                        return View(postback);
                    }


                    //檔案是否為圖片
                    if (!Models.Member.Member.IsPicture(file.FileName))
                    {
                        ViewBag.ResultMessage = "檔案不為圖片";
                        return View(postback);
                    }

                    //檔案是否為圖片
                    if (Models.Member.Member.IsImage(file) == null)
                    {
                        ViewBag.ResultMessage = "檔案不為圖片";
                        return View(postback);
                    }

                }

                if (this.ModelState.IsValid)
                {
                    if (!new Models.Member.Member().IsMemberidExist(postback.MemberID))
                    {
                        ViewBag.ResultMessage = "會員編號已存在";
                        return View(postback);
                    }
                    else
                    {
                        var result = new Models.Member.Member().Post_Member(postback, file, FileBytes, (string)Session["UserID"]);
                        if (result)
                        {
                            TempData["ResultMessage"] = String.Format("會員[{0}]成功新增", postback.MemberID);
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            ViewBag.ResultMessage = "資料有誤，請檢查";
                            return View(postback);
                        }
                    }

                }
                else
                {
                    ViewBag.ResultMessage = "資料有誤，請檢查";
                    return View(postback);
                }
            }
            catch (Exception e)
            {
                ViewBag.ResultMessage = e.ToString();
                return View();
            }
        }
    }
}

WebApplication1/WebApplication1/Views/Member/Create.cshtml
@model WebApplication1.Models.Member.Member

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}



@using (Html.BeginForm("Create", "Member", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>會員資料新增作業</h2>
        <hr />

        @if (ViewBag.ResultMessage != null)//判斷如果有訊息，則顯示。
        {
            //@Html.Label("info", (string)ViewBag.ResultMessage, new { @class = "text-info" })
            <script type="text/javascript">
            var message = @Html.Raw(Json.Encode(ViewBag.ResultMessage));
            alert(message);
            </script>
        }

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.MemberID, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MemberID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MemberID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MemberName, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MemberName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MemberName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MobilPhone, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MobilPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MobilPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMail, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageName, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.TextBox("file", "", new { type = "file", accept = ".jpg" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="存檔" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回清單", "Index")
</div>

WebApplication1/WebApplication1/Views/Member/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2>Delete</h2>

WebApplication1/WebApplication1/Views/Member/Edit.cshtml
@model WebApplication1.Models.Member.Member

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

@if (ViewBag.ResultMessage != null)//判斷如果有訊息，則顯示。
{
    //@Html.Label("info", (string)ViewBag.ResultMessage, new { @class = "text-info" })
    <script type="text/javascript">
            var message = @Html.Raw(Json.Encode(ViewBag.ResultMessage));
            alert(message);
    </script>
}

@using (Html.BeginForm("Edit", "Member", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <br></br>
        <h2>會員資料修改作業</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MemberID)


        <div class="form-group">
            <div class="col-md-2">
                @{
                    if (Model.MemberImage != null)
                    {
                        var base64 = Convert.ToBase64String(Model.MemberImage);
                        var imgSrc = String.Format("data:image/jpg;base64,{0}", base64);
                        <img src="@imgSrc" width="200" height="200" />
                    }
                    else
                    {
                        <img src="" width="200" height="200" />
                    }
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MemberID, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MemberID, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.MemberID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MemberName, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MemberName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MemberName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MobilPhone, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MobilPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MobilPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMail, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageName, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.TextBox("file", "", new { type = "file", accept = ".jpg" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="存檔" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回清單", "Index")
</div>

WebApplication1/WebApplication1/Views/Member/Index.cshtml
@model IEnumerable<WebApplication1.Models.Member.Member>
@using PagedList.Mvc;
@using PagedList;


@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<h2>會員資料管理作業</h2>
<br />

@if (ViewBag.ResultMessage != null)//判斷如果有訊息，則顯示。
{
    //@Html.Label("info", (string)ViewBag.ResultMessage, new { @class = "text-info" })
    <script type="text/javascript">
            var message = @Html.Raw(Json.Encode(ViewBag.ResultMessage));
            alert(message);
    </script>
}
<div class="container">
    <div class="row">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="table-responsive">
                <div id="toolbar">
                    <form class="form-inline">
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon">會員編號</div>
                                <input type="text" class="form-control" name="id" id="searchTexts" placeholder="請輸入會員編號">
                                <div class="column">
                                    <button type="submit" class="btn btn-primary queryButton"> 搜尋</button>
                                    @Html.ActionLink("新增會員", "Create", new { }, new { @class = "btn btn-primary" })
                                    <button type="button" class="btn btn-primary" id="ButtonExport" name="ButtonExport" onclick="ExportClick('Member')" >
                                        匯出資料
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div>

        }


    </div>
</div>


<table class="table">
    <tr>
        <th width="70">
            操作
        </th>
        <th width="70">
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().MemberID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().MemberName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().MobilPhone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().EMail)
        </th>
        <th>

        </th>
    </tr>

    @foreach (var md in this.Model)
    {
<tr>
    <td>
        @Html.ActionLink("編輯", "Edit", new { id = md.MemberID }, new { @class = "glyphicon glyphicon-pencil" })
    </td>
    <td>
        @Html.ActionLink("刪除", "Delete", new { id = md.MemberID }, new { @class = "glyphicon glyphicon-trash", @onclick = "return Confirm_Form('" + md.MemberID + "')" })
    </td>
    <td>@md.MemberID</td>
    <td>@md.MemberName</td>
    <td>@md.MobilPhone</td>
    <td>@md.EMail</td>
    <td></td>
</tr>
    }
</table>
@Html.PagedListPager((IPagedList)Model, x => Url.Action("Index", new { page = x }))

@section scripts
{
    <script type="text/javascript">
        function Confirm_Form(MemberID) {
            var message = "您確定要刪除會員編號" + MemberID + "嗎?";
            if (!confirm(message))
                return false;
        }
    </script>

    <script src="@RouteJs.RouteJsHandler.HandlerUrl"></script>
    <script src="~/Scripts/Export.js"></script>
    <script src="~/Scripts/bootbox.min.js"></script>
}