WebApplication1/WebApplication1/Models/Login/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MySql.Data.MySqlClient;

namespace WebApplication1.Models.Login
{

    public class Login
    {
        [Required]
        [Display(Name = "帳號")]
        [StringLength(10, ErrorMessage = "{0}的長度至少必須為{2}的字元。", MinimumLength = 4)]
        public string UserID { get; set; }

        [Required]
        [Display(Name = "密碼")]
        [StringLength(10, ErrorMessage = "{0}的長度至少必須為{2}的字元。", MinimumLength = 4)]
        [DataType(DataType.Password)]
        public string UserPwd { get; set; }

        public static string Encoded(string Code, int Length = 32)
        {
            string temp = "", PassWD = "", newcode1 = "", newcode2 = "", ReturnCode = "";
            for (int i = 1; i < Code.Length; i++)
            {
                if ((int)Code[i - 1] > 60)
                {
                    if (i % 2 == 0)
                        temp = Convert.ToString((((int)Code[i - 1] - 55) + 16) % 29 * 26);
                    else
                        temp = Convert.ToString((((int)Code[i - 1] - 55) + 9) % 26 * 29);
                }
                else
                {
                    if (i % 2 == 0)
                        temp = Convert.ToString((((int)Code[i - 1] - 48) + 7) % 17 * 9);
                    else
                        temp = Convert.ToString((((int)Code[i - 1] - 48) + 29) % 13 * 16);
                }
                PassWD += temp;
            }
            for (int i = 1; i < PassWD.Length; i++)
            {
                if (i % 2 == 0)
                    newcode1 += PassWD[i - 1];
                else
                    newcode2 += PassWD[i - 1];
            }
            PassWD = newcode1 + newcode2;

            if (PassWD != "")
            {
                while (PassWD.Length < 64)
                {
                    PassWD += PassWD;
                }
            }

            bool Out;
            for (int i = 1; i < PassWD.Length - 1; i = i + 2)
            {

                Out = int.TryParse(PassWD.Substring(i - 1, 2), out int CheckInt);
                if (!Out)
                    CheckInt = 0;

                CheckInt = CheckInt * i;
                if (CheckInt % 36 > 9)
                    CheckInt = CheckInt % 36 + 55;
                else
                    CheckInt = CheckInt % 36 + 48;
                ReturnCode += (char)CheckInt;
            }
            return ReturnCode.Substring(0, Length);
        }



        public static async System.Threading.Tasks.Task<bool> LoginAccountAsync(string userID, string receivePassword)
        {
          
            using (var conn = new MySqlConnection(GlobalFunction.GlobalConnString))
            {

                await conn.OpenAsync();

                using (var command = conn.CreateCommand())
                {
                    command.CommandText = "SELECT *  FROM employee WHERE EmployeeID = @ID and Passwd = @Password ;";
                    command.Parameters.AddWithValue("@ID", userID);
                    command.Parameters.AddWithValue("@Password", receivePassword);

                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        if (reader.HasRows)
                        {


                            return true;
                        }
                        else
                        {
                            return false;
                        }
                    }
                }
            }

        }
    }
}

WebApplication1/WebApplication1/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<ActionResult> Index(Models.Login.Login postback)
        {

            try
            {
                if (this.ModelState.IsValid)
                {
                    var receivePassword = Models.Login.Login.Encoded(postback.UserPwd + postback.UserID);
                    if (await Models.Login.Login.LoginAccountAsync(postback.UserID, receivePassword))
                    {
                        Session["UserID"] = postback.UserID;
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ModelState.AddModelError("password", "登入失敗，請確認登入資訊。");
                        return View("Index");
                    }
                }
                else
                {
                    // return RedirectToAction("Index", "Login");
                    return View("Index");
                }
            }
            catch (Exception e)
            {
                //ViewBag.ResultMessage = "連線失敗，請確認網路是否正常。";
                ViewBag.ResultMessage = e.ToString();
                return View();
            }



        }

        public ActionResult Logout()
        {
            Session.Clear();
            return View("Index");
        }
    }
}

WebApplication1/WebApplication1/Views/Login/Index.cshtml
@{
    /**/
    ViewBag.Title = "Npos使用者登入";
}

@model  WebApplication1.Models.Login.Login


<br>
<h3>Npos 管理系統</h3>

@if (ViewBag.ResultMessage != null)//判斷如果有訊息，則顯示。
{
    //@Html.Label("info", (string)ViewBag.ResultMessage, new { @class = "text-info" })
    <script type="text/javascript">
            var message = @Html.Raw(Json.Encode(ViewBag.ResultMessage));
            alert(message);
    </script>
}

@using (Html.BeginForm("Index", "Login", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <hr />
        <div class="" style="padding-top: 10px">
            <div class="column">
                @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <br></br>
        <div class="" style="padding-top: 10px">
            <div class="column">
                @Html.LabelFor(model => model.UserPwd, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserPwd, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserPwd, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="" style="padding-left: 40px;padding-top: 10px">
            @Html.ValidationMessage("password", null, new { @class = "text-danger", style = "margin-left:10px;" })
        </div>
        <form>
            <div style="padding-right: 70px; padding-top: 10px">
                <input id="Submit" type="submit" value="確定" style="padding: 5px 20px;margin-left:10px;">
            </div>
        </form>

    </div>
}